# Alternative GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  GLFW_config = debug
  ComputerGraphicsProject2023_config = debug

else ifeq ($(config),release)
  GLFW_config = release
  ComputerGraphicsProject2023_config = release

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := GLFW ComputerGraphicsProject2023

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

GLFW:
ifneq (,$(GLFW_config))
	@echo "==== Building GLFW ($(GLFW_config)) ===="
	@${MAKE} --no-print-directory -C ComputerGraphicsProject2023/vendor/GLFW -f Makefile config=$(GLFW_config)
endif

ComputerGraphicsProject2023: GLFW
ifneq (,$(ComputerGraphicsProject2023_config))
	@echo "==== Building ComputerGraphicsProject2023 ($(ComputerGraphicsProject2023_config)) ===="
	@${MAKE} --no-print-directory -C ComputerGraphicsProject2023 -f Makefile config=$(ComputerGraphicsProject2023_config)
endif

clean:
	@${MAKE} --no-print-directory -C ComputerGraphicsProject2023/vendor/GLFW -f Makefile clean
	@${MAKE} --no-print-directory -C ComputerGraphicsProject2023 -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   GLFW"
	@echo "   ComputerGraphicsProject2023"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"